DELETE http://localhost:3001/api/blogs/6a2726e55a643bb8d099f4e3
Authorization: Bearer eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJ1c2VybmFtZSI6InJvb3QiLCJpZCI6IjZhMjUwY2VjNzYyODA5NTFiYjc2ZDQ1ZiIsImlhdCI6MTc4MTg4NzE0MX0.UymlA6a-qUeTcxNPjBoy1JVBVuAXbGKh6-KOiuxNOJ4