POST http://localhost:3001/api/blogs
Content-Type: application/json

{
  "title": "Test blog without likes",
  "author": "Kerrie Ray",
  "url": "https://www.healthyfood.com/healthy-recipes/coconut-chicken-tenders-with-spinach-and-rice/"
}